### ISSUE TITLE
请问这个工具会在游戏界面中显示吗

### ISSUE THREAD

**Issue by luckoct** [WarriorFromLongAgo/xuegao-lol-skills#1]
rt

**Comment by WarriorFromLongAgo** [comment]
按下 tab 键显示，松开 tab 键消失。

所以也就是说，只会在你看地图的时候，显示。

最终回复：不会影响你的正常操作。

**Comment by luckoct** [comment]
好哒，谢谢啦，只可惜电脑没有java环境

**Comment by WarriorFromLongAgo** [comment]
不需要Java环境，你下载gitee的那个包，解压双击运行即可。
那个包，带了jre Java runtime（Java 运行环境）

**Comment by luckoct** [comment]
好的，谢谢啦
